server:
  port: 6061

spring:
  application:
    name: powersync-java
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_demo
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/library-system/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/library-system
            jwk-set-uri: http://localhost:8080/realms/library-system/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/library-system/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/library-system/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: frappe
            client-secret: aet0Ccp2GDN1zU9GjjI30uDu2iTsqEXl
            provider: keycloak
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/keycloak
            scope: openid,profile,email
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/library-system/protocol/openid-connect/certs