server:
  port: 6061
realm:
  name: master
  port: 8080
spring:
  application:
    name: powersync-java
  datasource:
    url: jdbc:postgresql://pg-db:5432/django_demo
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:${realm.port}/realms/${realm.name}/protocol/openid-connect/auth
            issuer-uri: http://localhost:${realm.port}/realms/${realm.name}
            jwk-set-uri: http://localhost:${realm.port}/realms/${realm.name}/protocol/openid-connect/certs
            token-uri: http://localhost:${realm.port}/realms/${realm.name}/protocol/openid-connect/token
            user-info-uri: http://localhost:${realm.port}/realms/${realm.name}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: frappe
            client-secret: aet0Ccp2GDN1zU9GjjI30uDu2iTsqEXl
            provider: keycloak
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/keycloak
            scope: openid,profile,email
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${realm.port}/realms/${realm.name}/protocol/openid-connect/certs