server:
  port: 6061
realm:
  name: master
  port: 8080
spring:
  application:
    name: powersync-java
  datasource:
    url: jdbc:postgresql://pg-db:5432/django_demo
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${realm.port}/realms/${realm.name}/protocol/openid-connect/certs